add memmy to apps list
LemmyNet/joinlemmy-site pull request #224
Opened 2023-07-14 16:31 UTC by Djones4822

2023-07-17 15:39 UTC, dessalines requested changes

2023-07-17 15:39 UTC, dessalines commented on src/assets/images/memmy_banner.png
Could you compress / make this file smaller?

2023-07-17 15:50 UTC, Djones4822 commented on src/assets/images/memmy_banner.png
Done, sorry about that! resized and converted to webp

2023-07-19 10:17 UTC, Nutomic approved these changes

2023-07-26 17:08 UTC, dessalines approved these changes

2023-07-26 17:08 UTC, merged