Adding Echo for Lemmy to apps list
LemmyNet/joinlemmy-site pull request #405
Opened 2024-10-13 00:33 UTC by fishcharlie

Not 100% sure I did this correctly. So please verify extra closely, and let me know if any adjustments are needed.

2024-10-14 08:03 UTC, Nutomic commented
It needs formatting, try running `npx prettier -w src`

2024-10-14 14:19 UTC, fishcharlie commented
@Nutomic Done. Sorry about that.

2024-10-14 14:53 UTC, fishcharlie commented on src/shared/components/app-definitions.ts
> +      link: "https://echo.rrainn.com/download/iphone",
```suggestion
      link: "https://apps.apple.com/us/app/echo-for-lemmy/id6450902296",
```

2024-10-14 22:19 UTC, dessalines commented on src/assets/images/echo_screen.png
Could you compress / shrink this file? You could use webp like the other files, or some kind of png compression program. Almost all these files are under 100 KB.

2024-10-15 19:39 UTC, dessalines requested changes
See comment above.

2024-10-16 02:46 UTC, fishcharlie commented
Just made that change.

2024-10-16 15:51 UTC, dessalines approved these changes
Sweet, thx!

2024-10-16 15:51 UTC, merged